[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
scholary_escrow = "2QyWqLBNUqhSz6ajW4UHA1YN6Wf35KCMdUmPEYBMvcNc"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
